##########
# based on collectionbuilder
# https://github.com/CollectionBuilder
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /digital
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/digital_source

# url to the shared assets folder on Digital
digital-assets: https://www.lib.uidaho.edu/assets
# directory for all centralize library media assets
lib-media: https://www.lib.uidaho.edu/media
# main url, used to point at server even when on dev server
liburl: https://www.lib.uidaho.edu

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Digital Collections, University of Idaho
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "University of Idaho Library Digital Collections provide access to unique materials to enhance and support research and education."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: University of Idaho, digital collections, history, archival research
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: uidaholib

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "University of Idaho Library Digital Initiatives"
organization-link: https://lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/images/ui_library_horizontal.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/library_white.png



# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]
